import {
  LayoutDashboard,
  UserCog,
  Receipt,
  WalletCards,
  Calculator,
  BarChart3,
  Users,
  FolderKanban,
  FileText,
  Clock3,
  ListTodo,
  Scale,
  Bell,
  ChartNoAxesCombined,
  Files,
} from "lucide-react";

export const dashboardConfig = [
  {
    appName: "Overview Dashboard",
    toUrl: "/dashboard",
    icon: LayoutDashboard,
    appStatus: "COMPLETED",
  },
  {
    appName: "Profile & Settings Dashboard",
    toUrl: "/profile",
    icon: UserCog,
    appStatus: "IN_PROGRESS",
  },
  {
    appName: "Invoices & Payments Dashboard",
    toUrl: "/invoices",
    icon: Receipt,
    appStatus: "COMPLETED",
  },
  {
    appName: "Expenses Dashboard",
    toUrl: "/expenses",
    icon: WalletCards,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Tax Estimator Dashboard",
    toUrl: "/tax-estimator",
    icon: Calculator,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Financial Reports Dashboard",
    toUrl: "/financial-reports",
    icon: BarChart3,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Clients Dashboard",
    toUrl: "/clients",
    icon: Users,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Projects/Contracts Dashboard",
    toUrl: "/projects",
    icon: FolderKanban,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Proposals Dashboard",
    toUrl: "/proposals",
    icon: FileText,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Time Tracking Dashboard",
    toUrl: "/time-tracking",
    icon: Clock3,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Task/To-Do Dashboard",
    toUrl: "/tasks",
    icon: ListTodo,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Contracts/Legal Dashboard",
    toUrl: "/contracts",
    icon: Scale,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Reminders Dashboard",
    toUrl: "/reminders",
    icon: Bell,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Analytics Dashboard",
    toUrl: "/analytics",
    icon: ChartNoAxesCombined,
    appStatus: "COMING_SOON",
  },
  {
    appName: "Document Templates Dashboard",
    toUrl: "/document-templates",
    icon: Files,
    appStatus: "COMING_SOON",
  },
];
